### ISSUE TITLE
The used apt syntax has been deprecated

### ISSUE THREAD

**Issue by pingvinen** [nover/ansible-role-ohmyzsh#7]
```
TASK [nover.ohmyzsh : Ensure zsh is installed] ****************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions 
is deprecated. Instead of using a loop to supply multiple items and specifying `name: 
"{{item}}"`, please use `name: ['git', 'git-core', 'zsh']` and remove the loop. This 
feature will be removed in version 2.11. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
```

The syntax should now be something like:

```
- name: Ensure zsh is installed
  apt:
    name: [git, git-core, zsh]
    state: present
    update_cache: yes
```
